// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZg9bpWavFo6g9C001RLV5yKemrl5bw2Q',
    appId: '1:674515989961:web:bb627488ac364129ae2418',
    messagingSenderId: '674515989961',
    projectId: 'nexus-game-app',
    authDomain: 'nexus-game-app.firebaseapp.com',
    storageBucket: 'nexus-game-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3LVWbBdf6D_v7TH1gAyNKKfaXNDxcpk4',
    appId: '1:674515989961:android:19403df2505b5027ae2418',
    messagingSenderId: '674515989961',
    projectId: 'nexus-game-app',
    storageBucket: 'nexus-game-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnnc3_HZe148znSpNDQ5o5mYFysW3Xwo',
    appId: '1:674515989961:ios:52b212999bfb52c3ae2418',
    messagingSenderId: '674515989961',
    projectId: 'nexus-game-app',
    storageBucket: 'nexus-game-app.firebasestorage.app',
    iosBundleId: 'com.example.nexusGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnnc3_HZe148znSpNDQ5o5mYFysW3Xwo',
    appId: '1:674515989961:ios:52b212999bfb52c3ae2418',
    messagingSenderId: '674515989961',
    projectId: 'nexus-game-app',
    storageBucket: 'nexus-game-app.firebasestorage.app',
    iosBundleId: 'com.example.nexusGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZg9bpWavFo6g9C001RLV5yKemrl5bw2Q',
    appId: '1:674515989961:web:df91b04835334358ae2418',
    messagingSenderId: '674515989961',
    projectId: 'nexus-game-app',
    authDomain: 'nexus-game-app.firebaseapp.com',
    storageBucket: 'nexus-game-app.firebasestorage.app',
  );
}
